#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("Droid.Resource", IsApplication=true)]

namespace Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::FacebookMonoDroid.Resource.String.library_name = global::Droid.Resource.String.library_name;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int androidPhotoMask = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ccvLogo = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int facebook_login = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Icon = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int shadow = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int thumbnailPlaceholder = 2130837509;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050000
			public const int about_PrimaryFragmentText = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int about_PrimaryFragmentWebView = 2131034113;
			
			// aapt resource value: 0x7f050014
			public const int activetask = 2131034132;
			
			// aapt resource value: 0x7f050037
			public const int address_background = 2131034167;
			
			// aapt resource value: 0x7f050040
			public const int birthdateText = 2131034176;
			
			// aapt resource value: 0x7f050006
			public const int bottom_border = 2131034118;
			
			// aapt resource value: 0x7f05004d
			public const int button = 2131034189;
			
			// aapt resource value: 0x7f050057
			public const int campus_container = 2131034199;
			
			// aapt resource value: 0x7f050058
			public const int campus_selection = 2131034200;
			
			// aapt resource value: 0x7f05000e
			public const int cancelButton = 2131034126;
			
			// aapt resource value: 0x7f050029
			public const int categorySpinner = 2131034153;
			
			// aapt resource value: 0x7f050019
			public const int ccv_logo = 2131034137;
			
			// aapt resource value: 0x7f050035
			public const int cellPhoneText = 2131034165;
			
			// aapt resource value: 0x7f05003a
			public const int cityAddressText = 2131034170;
			
			// aapt resource value: 0x7f05003b
			public const int city_border = 2131034171;
			
			// aapt resource value: 0x7f050034
			public const int contact_background = 2131034164;
			
			// aapt resource value: 0x7f050042
			public const int doneButton = 2131034178;
			
			// aapt resource value: 0x7f050012
			public const int dropShadowView = 2131034130;
			
			// aapt resource value: 0x7f050036
			public const int emailAddressText = 2131034166;
			
			// aapt resource value: 0x7f050056
			public const int end_seperator = 2131034198;
			
			// aapt resource value: 0x7f05000d
			public const int facebookButton = 2131034125;
			
			// aapt resource value: 0x7f050016
			public const int fadeOutView = 2131034134;
			
			// aapt resource value: 0x7f050010
			public const int fragment_container = 2131034128;
			
			// aapt resource value: 0x7f050017
			public const int fullscreen = 2131034135;
			
			// aapt resource value: 0x7f050041
			public const int genderText = 2131034177;
			
			// aapt resource value: 0x7f050002
			public const int give_PrimaryFragmentText = 2131034114;
			
			// aapt resource value: 0x7f05004e
			public const int icon = 2131034190;
			
			// aapt resource value: 0x7f050033
			public const int lastNameText = 2131034163;
			
			// aapt resource value: 0x7f05000a
			public const int loginButton = 2131034122;
			
			// aapt resource value: 0x7f05000c
			public const int loginResult = 2131034124;
			
			// aapt resource value: 0x7f050004
			public const int login_background = 2131034116;
			
			// aapt resource value: 0x7f05000f
			public const int login_progressBar = 2131034127;
			
			// aapt resource value: 0x7f050043
			public const int logoutButton = 2131034179;
			
			// aapt resource value: 0x7f05002d
			public const int makePublic = 2131034157;
			
			// aapt resource value: 0x7f05002e
			public const int makePublicSwitch = 2131034158;
			
			// aapt resource value: 0x7f050009
			public const int middle_border = 2131034121;
			
			// aapt resource value: 0x7f050023
			public const int name_background = 2131034147;
			
			// aapt resource value: 0x7f050013
			public const int navbar = 2131034131;
			
			// aapt resource value: 0x7f050003
			public const int navbar_border = 2131034115;
			
			// aapt resource value: 0x7f050018
			public const int navbar_relative_layout = 2131034136;
			
			// aapt resource value: 0x7f050015
			public const int navtoolbar = 2131034133;
			
			// aapt resource value: 0x7f05001a
			public const int news_details_details = 2131034138;
			
			// aapt resource value: 0x7f05001b
			public const int news_details_launch_url = 2131034139;
			
			// aapt resource value: 0x7f05001c
			public const int news_primary_list = 2131034140;
			
			// aapt resource value: 0x7f050032
			public const int nickNameText = 2131034162;
			
			// aapt resource value: 0x7f050020
			public const int notes_details_list = 2131034144;
			
			// aapt resource value: 0x7f050021
			public const int notes_primary_activityIndicator = 2131034145;
			
			// aapt resource value: 0x7f050022
			public const int notes_primary_list = 2131034146;
			
			// aapt resource value: 0x7f05001d
			public const int notes_relative_layout = 2131034141;
			
			// aapt resource value: 0x7f050007
			public const int passwordText = 2131034119;
			
			// aapt resource value: 0x7f05003f
			public const int personal_background = 2131034175;
			
			// aapt resource value: 0x7f05002b
			public const int postAnonymous = 2131034155;
			
			// aapt resource value: 0x7f05002c
			public const int postAnonymousSwitch = 2131034156;
			
			// aapt resource value: 0x7f050026
			public const int prayerRequest_background = 2131034150;
			
			// aapt resource value: 0x7f050030
			public const int prayer_create_activityIndicator = 2131034160;
			
			// aapt resource value: 0x7f050024
			public const int prayer_create_firstNameText = 2131034148;
			
			// aapt resource value: 0x7f050025
			public const int prayer_create_lastNameText = 2131034149;
			
			// aapt resource value: 0x7f050027
			public const int prayer_create_requestText = 2131034151;
			
			// aapt resource value: 0x7f05002f
			public const int prayer_create_submitButton = 2131034159;
			
			// aapt resource value: 0x7f050031
			public const int prayer_primary_activityIndicator = 2131034161;
			
			// aapt resource value: 0x7f05004a
			public const int profile_name = 2131034186;
			
			// aapt resource value: 0x7f050049
			public const int profile_prefix = 2131034185;
			
			// aapt resource value: 0x7f05001f
			public const int progressBar = 2131034143;
			
			// aapt resource value: 0x7f05001e
			public const int refreshButton = 2131034142;
			
			// aapt resource value: 0x7f05000b
			public const int registerButton = 2131034123;
			
			// aapt resource value: 0x7f050050
			public const int seperator = 2131034192;
			
			// aapt resource value: 0x7f050059
			public const int settings_button = 2131034201;
			
			// aapt resource value: 0x7f050028
			public const int spinner_background = 2131034152;
			
			// aapt resource value: 0x7f050011
			public const int springboard = 2131034129;
			
			// aapt resource value: 0x7f050055
			public const int springboard_about_frame = 2131034197;
			
			// aapt resource value: 0x7f05004b
			public const int springboard_container = 2131034187;
			
			// aapt resource value: 0x7f050054
			public const int springboard_give_frame = 2131034196;
			
			// aapt resource value: 0x7f050051
			public const int springboard_groupfinder_frame = 2131034193;
			
			// aapt resource value: 0x7f050048
			public const int springboard_login_button = 2131034184;
			
			// aapt resource value: 0x7f05004c
			public const int springboard_news_frame = 2131034188;
			
			// aapt resource value: 0x7f050052
			public const int springboard_notes_frame = 2131034194;
			
			// aapt resource value: 0x7f050053
			public const int springboard_prayer_frame = 2131034195;
			
			// aapt resource value: 0x7f050047
			public const int springboard_profile_image = 2131034183;
			
			// aapt resource value: 0x7f050045
			public const int springboard_profile_image_container = 2131034181;
			
			// aapt resource value: 0x7f050046
			public const int springboard_profile_image_layout = 2131034182;
			
			// aapt resource value: 0x7f050044
			public const int springboard_relative_layout = 2131034180;
			
			// aapt resource value: 0x7f05003c
			public const int stateAddressText = 2131034172;
			
			// aapt resource value: 0x7f05003d
			public const int state_border = 2131034173;
			
			// aapt resource value: 0x7f050038
			public const int streetAddressText = 2131034168;
			
			// aapt resource value: 0x7f050039
			public const int street_border = 2131034169;
			
			// aapt resource value: 0x7f05002a
			public const int switch_background = 2131034154;
			
			// aapt resource value: 0x7f05004f
			public const int text = 2131034191;
			
			// aapt resource value: 0x7f050005
			public const int top_border = 2131034117;
			
			// aapt resource value: 0x7f050008
			public const int usernameText = 2131034120;
			
			// aapt resource value: 0x7f05003e
			public const int zipAddressText = 2131034174;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int About_Primary = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Give_Primary = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int ImageCrop = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Login = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Main = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int navbar = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int News_Details = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int News_Primary = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int Notes = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int Notes_Details = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int Notes_Primary = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int Prayer_Create = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int Prayer_Primary = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int Profile = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int Springboard = 2130903054;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040002
			public const int app_name = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int hello = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int library_name = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
