#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("Droid.Resource", IsApplication=true)]

namespace Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ccvLogo = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int groupfinder = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Icon = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int info = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int noprofile = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int notes = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int prayer = 2130837510;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050003
			public const int activetask = 2131034115;
			
			// aapt resource value: 0x7f05000a
			public const int detailsButton = 2131034122;
			
			// aapt resource value: 0x7f050000
			public const int fragment_container = 2131034112;
			
			// aapt resource value: 0x7f050007
			public const int linearLayout = 2131034119;
			
			// aapt resource value: 0x7f05000b
			public const int linear_layout = 2131034123;
			
			// aapt resource value: 0x7f050006
			public const int moreDetailsButton = 2131034118;
			
			// aapt resource value: 0x7f050002
			public const int navbar = 2131034114;
			
			// aapt resource value: 0x7f050004
			public const int navtoolbar = 2131034116;
			
			// aapt resource value: 0x7f05000c
			public const int profile_image = 2131034124;
			
			// aapt resource value: 0x7f050009
			public const int progressBar = 2131034121;
			
			// aapt resource value: 0x7f050008
			public const int refreshButton = 2131034120;
			
			// aapt resource value: 0x7f050001
			public const int springboard = 2131034113;
			
			// aapt resource value: 0x7f05001f
			public const int springboard_about_button = 2131034143;
			
			// aapt resource value: 0x7f05001e
			public const int springboard_about_frame = 2131034142;
			
			// aapt resource value: 0x7f050020
			public const int springboard_about_icon = 2131034144;
			
			// aapt resource value: 0x7f050021
			public const int springboard_about_text = 2131034145;
			
			// aapt resource value: 0x7f050013
			public const int springboard_groupfinder_button = 2131034131;
			
			// aapt resource value: 0x7f050012
			public const int springboard_groupfinder_frame = 2131034130;
			
			// aapt resource value: 0x7f050014
			public const int springboard_groupfinder_icon = 2131034132;
			
			// aapt resource value: 0x7f050015
			public const int springboard_groupfinder_text = 2131034133;
			
			// aapt resource value: 0x7f05000d
			public const int springboard_login_text = 2131034125;
			
			// aapt resource value: 0x7f05000f
			public const int springboard_news_button = 2131034127;
			
			// aapt resource value: 0x7f05000e
			public const int springboard_news_frame = 2131034126;
			
			// aapt resource value: 0x7f050010
			public const int springboard_news_icon = 2131034128;
			
			// aapt resource value: 0x7f050011
			public const int springboard_news_text = 2131034129;
			
			// aapt resource value: 0x7f05001b
			public const int springboard_notes_button = 2131034139;
			
			// aapt resource value: 0x7f05001a
			public const int springboard_notes_frame = 2131034138;
			
			// aapt resource value: 0x7f05001c
			public const int springboard_notes_icon = 2131034140;
			
			// aapt resource value: 0x7f05001d
			public const int springboard_notes_text = 2131034141;
			
			// aapt resource value: 0x7f050017
			public const int springboard_prayer_button = 2131034135;
			
			// aapt resource value: 0x7f050016
			public const int springboard_prayer_frame = 2131034134;
			
			// aapt resource value: 0x7f050018
			public const int springboard_prayer_icon = 2131034136;
			
			// aapt resource value: 0x7f050019
			public const int springboard_prayer_text = 2131034137;
			
			// aapt resource value: 0x7f050005
			public const int textView1 = 2131034117;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int News_Details = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Notes = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int PrimaryNews = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Springboard = 2130903044;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int app_name = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
