#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("Droid.Resource", IsApplication=true)]

namespace Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::FacebookMonoDroid.Resource.String.library_name = global::Droid.Resource.String.library_name;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int androidPhotoMask = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ccvLogo = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int dark_cursor = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int facebook_login = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Icon = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int light_cursor = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int shadow = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int thumbnailPlaceholder = 2130837511;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060000
			public const int about_PrimaryFragmentText = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int about_PrimaryFragmentWebView = 2131099649;
			
			// aapt resource value: 0x7f060014
			public const int activetask = 2131099668;
			
			// aapt resource value: 0x7f060025
			public const int activityIndicator = 2131099685;
			
			// aapt resource value: 0x7f06003a
			public const int address_background = 2131099706;
			
			// aapt resource value: 0x7f060044
			public const int birthdateButton = 2131099716;
			
			// aapt resource value: 0x7f060043
			public const int birthdateText = 2131099715;
			
			// aapt resource value: 0x7f060006
			public const int bottom_border = 2131099654;
			
			// aapt resource value: 0x7f060054
			public const int button = 2131099732;
			
			// aapt resource value: 0x7f06005e
			public const int campus_container = 2131099742;
			
			// aapt resource value: 0x7f06005f
			public const int campus_selection = 2131099743;
			
			// aapt resource value: 0x7f06000e
			public const int cancelButton = 2131099662;
			
			// aapt resource value: 0x7f06002c
			public const int categorySpinner = 2131099692;
			
			// aapt resource value: 0x7f060019
			public const int ccv_logo = 2131099673;
			
			// aapt resource value: 0x7f060039
			public const int cellPhoneText = 2131099705;
			
			// aapt resource value: 0x7f06003d
			public const int cityAddressText = 2131099709;
			
			// aapt resource value: 0x7f06003e
			public const int city_border = 2131099710;
			
			// aapt resource value: 0x7f060037
			public const int contact_background = 2131099703;
			
			// aapt resource value: 0x7f060047
			public const int doneButton = 2131099719;
			
			// aapt resource value: 0x7f060012
			public const int dropShadowView = 2131099666;
			
			// aapt resource value: 0x7f060038
			public const int emailAddressText = 2131099704;
			
			// aapt resource value: 0x7f06005d
			public const int end_seperator = 2131099741;
			
			// aapt resource value: 0x7f06000d
			public const int facebookButton = 2131099661;
			
			// aapt resource value: 0x7f060016
			public const int fadeOutView = 2131099670;
			
			// aapt resource value: 0x7f060010
			public const int fragment_container = 2131099664;
			
			// aapt resource value: 0x7f060017
			public const int fullscreen = 2131099671;
			
			// aapt resource value: 0x7f060046
			public const int genderButton = 2131099718;
			
			// aapt resource value: 0x7f060045
			public const int genderText = 2131099717;
			
			// aapt resource value: 0x7f060002
			public const int give_PrimaryFragmentText = 2131099650;
			
			// aapt resource value: 0x7f060055
			public const int icon = 2131099733;
			
			// aapt resource value: 0x7f060036
			public const int lastNameText = 2131099702;
			
			// aapt resource value: 0x7f06000a
			public const int loginButton = 2131099658;
			
			// aapt resource value: 0x7f06000c
			public const int loginResult = 2131099660;
			
			// aapt resource value: 0x7f060004
			public const int login_background = 2131099652;
			
			// aapt resource value: 0x7f06000f
			public const int login_progressBar = 2131099663;
			
			// aapt resource value: 0x7f060048
			public const int logoutButton = 2131099720;
			
			// aapt resource value: 0x7f060030
			public const int makePublic = 2131099696;
			
			// aapt resource value: 0x7f060031
			public const int makePublicSwitch = 2131099697;
			
			// aapt resource value: 0x7f060009
			public const int middle_border = 2131099657;
			
			// aapt resource value: 0x7f060026
			public const int name_background = 2131099686;
			
			// aapt resource value: 0x7f060013
			public const int navbar = 2131099667;
			
			// aapt resource value: 0x7f060003
			public const int navbar_border = 2131099651;
			
			// aapt resource value: 0x7f060018
			public const int navbar_relative_layout = 2131099672;
			
			// aapt resource value: 0x7f060015
			public const int navtoolbar = 2131099669;
			
			// aapt resource value: 0x7f06001b
			public const int news_details_details = 2131099675;
			
			// aapt resource value: 0x7f06001c
			public const int news_details_launch_url = 2131099676;
			
			// aapt resource value: 0x7f06001a
			public const int news_details_title = 2131099674;
			
			// aapt resource value: 0x7f06001d
			public const int news_primary_list = 2131099677;
			
			// aapt resource value: 0x7f060035
			public const int nickNameText = 2131099701;
			
			// aapt resource value: 0x7f060021
			public const int notes_details_list = 2131099681;
			
			// aapt resource value: 0x7f060022
			public const int notes_primary_activityIndicator = 2131099682;
			
			// aapt resource value: 0x7f060023
			public const int notes_primary_list = 2131099683;
			
			// aapt resource value: 0x7f06001e
			public const int notes_relative_layout = 2131099678;
			
			// aapt resource value: 0x7f060007
			public const int passwordText = 2131099655;
			
			// aapt resource value: 0x7f060042
			public const int personal_background = 2131099714;
			
			// aapt resource value: 0x7f06002e
			public const int postAnonymous = 2131099694;
			
			// aapt resource value: 0x7f06002f
			public const int postAnonymousSwitch = 2131099695;
			
			// aapt resource value: 0x7f060029
			public const int prayerRequest_background = 2131099689;
			
			// aapt resource value: 0x7f060033
			public const int prayer_create_activityIndicator = 2131099699;
			
			// aapt resource value: 0x7f060027
			public const int prayer_create_firstNameText = 2131099687;
			
			// aapt resource value: 0x7f060028
			public const int prayer_create_lastNameText = 2131099688;
			
			// aapt resource value: 0x7f06002a
			public const int prayer_create_requestText = 2131099690;
			
			// aapt resource value: 0x7f060032
			public const int prayer_create_submitButton = 2131099698;
			
			// aapt resource value: 0x7f060034
			public const int prayer_primary_activityIndicator = 2131099700;
			
			// aapt resource value: 0x7f060050
			public const int profile_name = 2131099728;
			
			// aapt resource value: 0x7f06004e
			public const int profile_name_linearlayout = 2131099726;
			
			// aapt resource value: 0x7f06004f
			public const int profile_prefix = 2131099727;
			
			// aapt resource value: 0x7f060020
			public const int progressBar = 2131099680;
			
			// aapt resource value: 0x7f06001f
			public const int refreshButton = 2131099679;
			
			// aapt resource value: 0x7f06000b
			public const int registerButton = 2131099659;
			
			// aapt resource value: 0x7f060057
			public const int seperator = 2131099735;
			
			// aapt resource value: 0x7f060060
			public const int settings_button = 2131099744;
			
			// aapt resource value: 0x7f06002b
			public const int spinner_background = 2131099691;
			
			// aapt resource value: 0x7f060011
			public const int springboard = 2131099665;
			
			// aapt resource value: 0x7f06005c
			public const int springboard_about_frame = 2131099740;
			
			// aapt resource value: 0x7f060052
			public const int springboard_container = 2131099730;
			
			// aapt resource value: 0x7f06005b
			public const int springboard_give_frame = 2131099739;
			
			// aapt resource value: 0x7f060058
			public const int springboard_groupfinder_frame = 2131099736;
			
			// aapt resource value: 0x7f06004d
			public const int springboard_login_button = 2131099725;
			
			// aapt resource value: 0x7f060053
			public const int springboard_news_frame = 2131099731;
			
			// aapt resource value: 0x7f060059
			public const int springboard_notes_frame = 2131099737;
			
			// aapt resource value: 0x7f06005a
			public const int springboard_prayer_frame = 2131099738;
			
			// aapt resource value: 0x7f06004c
			public const int springboard_profile_image = 2131099724;
			
			// aapt resource value: 0x7f06004a
			public const int springboard_profile_image_container = 2131099722;
			
			// aapt resource value: 0x7f06004b
			public const int springboard_profile_image_layout = 2131099723;
			
			// aapt resource value: 0x7f060049
			public const int springboard_relative_layout = 2131099721;
			
			// aapt resource value: 0x7f06003f
			public const int stateAddressText = 2131099711;
			
			// aapt resource value: 0x7f060040
			public const int state_border = 2131099712;
			
			// aapt resource value: 0x7f06003b
			public const int streetAddressText = 2131099707;
			
			// aapt resource value: 0x7f06003c
			public const int street_border = 2131099708;
			
			// aapt resource value: 0x7f06002d
			public const int switch_background = 2131099693;
			
			// aapt resource value: 0x7f060056
			public const int text = 2131099734;
			
			// aapt resource value: 0x7f060005
			public const int top_border = 2131099653;
			
			// aapt resource value: 0x7f060008
			public const int usernameText = 2131099656;
			
			// aapt resource value: 0x7f060051
			public const int view_profile = 2131099729;
			
			// aapt resource value: 0x7f060024
			public const int webView = 2131099684;
			
			// aapt resource value: 0x7f060041
			public const int zipAddressText = 2131099713;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int About_Primary = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int DatePicker = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Give_Primary = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int ImageCrop = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Login = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Main = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int navbar = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int News_Details = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int News_Primary = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int Notes = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int Notes_Details = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int Notes_Primary = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int Notes_WebView = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int Prayer_Create = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int Prayer_Primary = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int Profile = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int Springboard = 2130903056;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040002
			public const int app_name = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int hello = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int library_name = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int CCVMobileTheme = 2131034112;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
